namespace spotivy_app.spotivy
{
    public class Constants
    {
        public enum Genre
       {  
           Pop = 0,  
           Rock = 1,  
           HipHop = 2,  
           Rap = 3,  
           RnB = 4,  
           Jazz = 5,  
           Blues = 6,  
           Classical = 7,  
           Country = 8,  
           Electronic = 9,  
           Dance = 10,  
           House = 11,  
           Techno = 12,  
           Trance = 13,  
           Dubstep = 14,  
           DrumAndBass = 15,  
           Reggae = 16,  
           Ska = 17,  
           Metal = 18,  
           Punk = 19,  
           Alternative = 20,  
           Indie = 21,  
           Folk = 22,  
           Soul = 23,  
           Funk = 24,  
           Disco = 25,  
           Gospel = 26,  
           Opera = 27,  
           Latin = 28,  
           Salsa = 29,  
           Reggaeton = 30,  
           KPop = 31,  
           JPop = 32,  
           World = 33,  
           Ambient = 34,  
           Chillout = 35,  
           Soundtrack = 36,  
           Musical = 37,  
           Children = 38,  
           Comedy = 39,  
           SpokenWord = 40,  
           Experimental = 41,  
           NewAge = 42,  
           Grunge = 43,  
           LoFi = 44,  
           Synthpop = 45,  
           Industrial = 46,  
           Emo = 47,  
           Bluegrass = 48,  
           Afrobeat = 49,  
           Trap = 50  
       }
}  
}
